apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storyteller
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: storyteller
    newName: rg.fr-par.scw.cloud/djnd/storyteller
    newTag: '1a78b41be79ac6a1a1f09aca4ae59bc9c0ecfca4'
