apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storyteller
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: storyteller
    newName: rg.fr-par.scw.cloud/djnd/storyteller
    newTag: 'd5d2c8b64f4f3d6e3f33df40409d13c3c57378b7'
