apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storyteller
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: storyteller
    newName: rg.fr-par.scw.cloud/djnd/storyteller
    newTag: '8bbe80632eb8d301805729dfdf617f687a60ad9a'
