# Generated by Django 5.2.7 on 2025-11-19 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GenVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "start_prompt",
                    models.TextField(
                        blank=True,
                        help_text="Initial prompt for video generation",
                        null=True,
                    ),
                ),
                ("scenario", models.TextField(blank=True, null=True)),
                (
                    "prompt",
                    models.TextField(
                        default="Vrni mi samo text iz scenarija, da ga lahko pošljem v TTS."
                    ),
                ),
                ("content_script", models.TextField(blank=True, null=True)),
                (
                    "voice_model",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "voice_file",
                    models.FileField(
                        blank=True,
                        help_text="Voice file generated by LLM",
                        null=True,
                        upload_to="voice_files/",
                    ),
                ),
                (
                    "srt_file",
                    models.FileField(
                        blank=True,
                        help_text="Subtitle file in SRT format",
                        null=True,
                        upload_to="srt_files/",
                    ),
                ),
                (
                    "srt_content",
                    models.TextField(
                        blank=True,
                        help_text="Content of the SRT subtitle file",
                        null=True,
                    ),
                ),
                (
                    "final_file",
                    models.FileField(
                        blank=True,
                        help_text="Final generated video file",
                        null=True,
                        upload_to="final_videos/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Ustvarjen"),
                            ("GENERATING_SCENARIO", "Generiranje scenarija"),
                            ("SCENARIO_READY", "Scenarij pripravljen"),
                            ("GENERATING_SCRIPT", "Generiranje skripta"),
                            ("SCRIPT_READY", "Skript pripravljen"),
                            ("GENERATING_VOICE", "Generiranje zvoka"),
                            ("VOICE_READY", "Zvok pripravljen"),
                            ("GENERATING_SUBTITLES", "Generiranje podnapisov"),
                            ("SUBTITLES_READY", "Podnapisi pripravljeni"),
                            ("GENERATING_SEGMENTS", "Generiranje segmentov"),
                            ("SEGMENTS_READY", "Segmenti pripravljeni"),
                            ("SELECTING_VIDEOS", "Izbiranje video klipov"),
                            ("VIDEOS_SELECTED", "Video klipi izbrani"),
                            ("RENDERING", "Renderiranje končnega videa"),
                            ("COMPLETED", "Končano"),
                            ("FAILED", "Napaka"),
                        ],
                        default="CREATED",
                        max_length=30,
                    ),
                ),
                ("result_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "video_segments_prompt",
                    models.TextField(
                        blank=True,
                        default="\nSpodaj imaš scenarij videa in transkript scenarija.\nVsebino mi razbij v 3-4 segmente in določi keyworde v angleščini, ki najbolje opisujejo vsebino, po katerih lahko nato iščem videe.\n",
                        help_text='\nPrompt za določitev ključnih segmentov videa. Na koncu prompta se bo še dodal text:\nZa vsak segment mi določi še start in endtime Vrni mi samo python seznam slovarjev v obliki \n[{{"start": "0.00", "end": "5.00", "text": "besedilo", "keywords": ["keyword_eng_1", "keyword_eng_2"]}}, ...]\n',
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VideoSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(help_text="Text of the segment")),
                (
                    "order",
                    models.IntegerField(help_text="Order of the segment in the video"),
                ),
                (
                    "query",
                    models.TextField(
                        help_text="Query used to retrieve or generate the scene"
                    ),
                ),
                ("start_time", models.FloatField(help_text="Start time in seconds")),
                ("end_time", models.FloatField(help_text="End time in seconds")),
                (
                    "cut_start_time",
                    models.FloatField(
                        blank=True,
                        help_text="Adjusted start time for cutting the scene",
                        null=True,
                    ),
                ),
                (
                    "cut_end_time",
                    models.FloatField(
                        blank=True,
                        help_text="Adjusted end time for cutting the scene",
                        null=True,
                    ),
                ),
                (
                    "video_proposals",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of video proposals with metadata",
                    ),
                ),
                (
                    "video_file",
                    models.FileField(
                        blank=True,
                        help_text="Video file for this segment",
                        null=True,
                        upload_to="video_segments/",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="agent.genvideo",
                    ),
                ),
            ],
        ),
    ]
