# Generated by Django 5.2.7 on 2025-11-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="genvideo",
            old_name="content_script",
            new_name="modify_prompt",
        ),
        migrations.RemoveField(
            model_name="genvideo",
            name="start_prompt",
        ),
        migrations.AlterField(
            model_name="genvideo",
            name="prompt",
            field=models.TextField(
                default='"Pripravi mi text iz scenarija, ki je podan spodaj, tako da ga lahko pošljem v TTS sistem za generacijo govora.\nIzpis naj bo formatiran kot navaden text brez dodatnih oznak ali formatiranja.\n'
            ),
        ),
    ]
