# Generated by Django 5.2.7 on 2025-11-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0002_rename_content_script_genvideo_modify_prompt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="genvideo",
            name="subtitle_style",
            field=models.CharField(
                default="style1",
                help_text="Selected subtitle style for video rendering",
                max_length=50,
            ),
        ),
    ]
