# Generated by Django 5.2.7 on 2025-11-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0003_genvideo_subtitle_style"),
    ]

    operations = [
        migrations.AddField(
            model_name="genvideo",
            name="subtitle_font_size",
            field=models.IntegerField(
                default=36, help_text="Font size for subtitles (in pixels)"
            ),
        ),
    ]
