# Generated by Django 5.2.7 on 2025-11-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0004_genvideo_subtitle_font_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="genvideo",
            name="subtitle_font_family",
            field=models.CharField(
                default="Montserrat",
                help_text="Font family for subtitles",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="genvideo",
            name="subtitle_font_weight",
            field=models.CharField(
                default="900", help_text="Font weight for subtitles", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="genvideo",
            name="subtitle_shadow",
            field=models.IntegerField(
                default=1, help_text="Shadow intensity for subtitles"
            ),
        ),
        migrations.AddField(
            model_name="genvideo",
            name="subtitle_stroke_weight",
            field=models.IntegerField(
                default=3, help_text="Stroke weight for subtitles (in pixels)"
            ),
        ),
        migrations.AlterField(
            model_name="genvideo",
            name="subtitle_font_size",
            field=models.IntegerField(
                default=20, help_text="Font size for subtitles (in pixels)"
            ),
        ),
    ]
