# Generated by Django 5.2.7 on 2025-11-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0005_genvideo_subtitle_font_family_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="genvideo",
            name="subtitle_vertical_position",
            field=models.IntegerField(
                default=10,
                help_text="Vertical position from bottom in percentage (0-50)",
            ),
        ),
        migrations.AlterField(
            model_name="genvideo",
            name="subtitle_font_size",
            field=models.IntegerField(
                default=12, help_text="Font size for subtitles (in pixels)"
            ),
        ),
    ]
