# Generated by Django 5.2.7 on 2025-11-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0006_genvideo_subtitle_vertical_position_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="genvideo",
            name="voice_duration",
            field=models.FloatField(
                blank=True, help_text="Duration of voice file in seconds", null=True
            ),
        ),
    ]
