# Generated by Django 5.2.7 on 2025-12-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0007_genvideo_voice_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="genvideo",
            name="error_details",
            field=models.TextField(
                blank=True, help_text="Error details if task failed", null=True
            ),
        ),
    ]
