# Generated by Django 5.2.7 on 2025-12-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0008_genvideo_error_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="genvideo",
            name="error_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("VOICE_GENERATION", "Napaka pri generiranju zvoka"),
                    ("SRT_GENERATION", "Napaka pri generiranju podnapisov"),
                    ("SEGMENTS_GENERATION", "Napaka pri generiranju segmentov"),
                    ("RENDERING", "Napaka pri renderiranju videa"),
                ],
                help_text="Type/stage of error",
                max_length=50,
                null=True,
            ),
        ),
    ]
