# Generated by Django 5.2.7 on 2026-01-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0009_genvideo_error_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videosegment",
            name="video_file",
        ),
        migrations.AlterField(
            model_name="genvideo",
            name="video_segments_prompt",
            field=models.TextField(
                blank=True,
                default="\nSpodaj imaš transkript scenarija za video in podnapise.\nTekst scenarija razbij v krajše, vsebinsko smiselne segmente in določi kratke ključne besede v angleščini, ki najbolje opisujejo vsebino posameznega segmenta.\nPri določanju ključnih besed upoštevaj tudi kontekst vsebine celotnega scenarija, ne samo posameznih segmentov.\n",
                help_text='\nPrompt za določitev ključnih segmentov videa. Na koncu prompta se bo še dodal text:\nZa vsak segment mi določi še start in endtime Vrni mi samo python seznam slovarjev v obliki \n[{{"start": "0.00", "end": "5.00", "text": "besedilo", "keywords": ["keyword_eng_1", "keyword_eng_2"]}}, ...]\n',
                null=True,
            ),
        ),
    ]
