# Generated by Django 5.2.7 on 2026-06-02 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0011_userslogo"),
    ]

    operations = [
        migrations.AddField(
            model_name="genvideo",
            name="logo",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional logo to include in the video",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="agent.userslogo",
            ),
        ),
    ]
