# Generated by Django 5.2.7 on 2026-06-02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0012_genvideo_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="genvideo",
            name="logo_position",
            field=models.CharField(
                choices=[("top_left", "Zgoraj levo"), ("top_right", "Zgoraj desno")],
                default="top_right",
                help_text="Selected corner for logo placement",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="genvideo",
            name="logo_size_percent",
            field=models.PositiveSmallIntegerField(
                default=15,
                help_text="Logo width as percentage of final video width",
                validators=[
                    django.core.validators.MinValueValidator(5),
                    django.core.validators.MaxValueValidator(40),
                ],
            ),
        ),
    ]
