# Generated by Django 5.2.7 on 2026-06-03

import django.conf.global_settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0013_genvideo_logo_position_genvideo_logo_size_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="genvideo",
            name="language",
            field=models.CharField(
                choices=django.conf.global_settings.LANGUAGES,
                default="sl",
                help_text="Language code used for voice generation",
                max_length=10,
            ),
        ),
    ]
