# Generated by Django 5.2.7 on 2026-06-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0014_genvideo_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="genvideo",
            name="subtitle_max_words_per_screen",
            field=models.IntegerField(
                blank=True,
                help_text="Maximum number of words displayed on screen at once",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="genvideo",
            name="language",
            field=models.CharField(
                choices=[("sl", "Slovenian"), ("en", "English")],
                default="sl",
                help_text="Language code used for voice generation",
                max_length=10,
            ),
        ),
    ]
