# Generated by Django 5.2.7 on 2026-06-18 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0015_genvideo_subtitle_max_words_per_screen_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderTTSModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("elevenlabs", "ElevenLabs"),
                            ("openai", "OpenAI"),
                            ("gemini", "Gemini"),
                        ],
                        max_length=30,
                    ),
                ),
                ("external_id", models.CharField(max_length=120)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("can_do_text_to_speech", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["provider", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "external_id"),
                        name="uniq_provider_tts_model",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProviderTTSModelLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language_id", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=120)),
                (
                    "tts_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="languages",
                        to="agent.providerttsmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["tts_model", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tts_model", "language_id"),
                        name="uniq_tts_model_language",
                    )
                ],
            },
        ),
    ]
