# Generated by Django 5.2.7 on 2026-06-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0016_providerttsmodel_providerttsmodellanguage"),
    ]

    operations = [
        migrations.AddField(
            model_name="genvideo",
            name="progress",
            field=models.CharField(
                blank=True,
                help_text="Optional field to store progress details for long-running tasks",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="genvideo",
            name="error_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("VOICE_GENERATION", "Napaka pri generiranju zvoka"),
                    ("SRT_GENERATION", "Napaka pri generiranju podnapisov"),
                    ("SEGMENTS_GENERATION", "Napaka pri generiranju segmentov"),
                    ("RENDERING", "Napaka pri renderiranju videa"),
                    ("TIMEOUT", "Timeout pri renderiranju videa"),
                ],
                help_text="Type/stage of error",
                max_length=50,
                null=True,
            ),
        ),
    ]
