# Generated by Django 5.2.7 on 2026-06-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0017_genvideo_progress_alter_genvideo_error_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genvideo",
            name="progress",
            field=models.CharField(
                default="",
                help_text="Optional field to store progress details for long-running tasks",
                max_length=255,
            ),
        ),
    ]
