# Generated by Django 5.2.7 on 2026-07-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0018_alter_genvideo_progress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genvideo",
            name="subtitle_font_size",
            field=models.IntegerField(
                default=20, help_text="Font size for subtitles (in pixels)"
            ),
        ),
        migrations.AlterField(
            model_name="genvideo",
            name="subtitle_font_weight",
            field=models.CharField(
                default="700", help_text="Font weight for subtitles", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="genvideo",
            name="subtitle_shadow",
            field=models.IntegerField(
                default=0, help_text="Shadow intensity for subtitles"
            ),
        ),
        migrations.AlterField(
            model_name="genvideo",
            name="subtitle_stroke_weight",
            field=models.IntegerField(
                default=2, help_text="Stroke weight for subtitles (in pixels)"
            ),
        ),
        migrations.AlterField(
            model_name="genvideo",
            name="subtitle_vertical_position",
            field=models.IntegerField(
                default=15,
                help_text="Vertical position from bottom in percentage (0-50)",
            ),
        ),
    ]
