# Generated by Django 5.2.7 on 2026-07-31 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0019_alter_genvideo_subtitle_font_size_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipkoRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipko_task_id",
                    models.CharField(
                        help_text="Task ID returned by Tipko API", max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="PENDING",
                        help_text="Current status of the Tipko request",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tipko_requests",
                        to="agent.genvideo",
                    ),
                ),
            ],
        ),
    ]
