# Generated by Django 5.2.7 on 2026-08-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0020_tipkorequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="genvideo",
            name="elevenlabs_alignment",
            field=models.JSONField(
                blank=True,
                help_text="Character timings returned by ElevenLabs TTS for local SRT regeneration",
                null=True,
            ),
        ),
    ]
