# Generated by Django 5.2.7 on 2026-08-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0021_genvideo_elevenlabs_alignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="genvideo",
            name="last_recovery_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When interrupted processing was last scheduled for recovery",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="genvideo",
            name="recovery_attempts",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Automatic restart recovery attempts for interrupted processing",
            ),
        ),
        migrations.AddField(
            model_name="genvideo",
            name="recovery_claimed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Temporary lease that prevents duplicate recovery scheduling",
                null=True,
            ),
        ),
    ]
