# Generated by Django 5.2.7 on 2026-08-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0022_genvideo_recovery_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genvideo",
            name="error_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("VOICE_GENERATION", "Napaka pri generiranju zvoka"),
                    ("SRT_GENERATION", "Napaka pri generiranju podnapisov"),
                    ("SEGMENTS_GENERATION", "Napaka pri generiranju segmentov"),
                    ("RENDERING", "Napaka pri renderiranju videa"),
                    ("TIMEOUT", "Timeout pri renderiranju videa"),
                    ("RECOVERY", "Samodejna obnovitev prekinjenega opravila"),
                ],
                help_text="Type/stage of error",
                max_length=50,
                null=True,
            ),
        ),
    ]