from django.conf import global_settings, settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils.translation import gettext_lazy as _

# Create your models here.


class GenVideo(models.Model):
    class Statuses(models.TextChoices):
        CREATED = "CREATED", _("Ustvarjen")
        GENERATING_SCENARIO = "GENERATING_SCENARIO", _("Generiranje scenarija")
        SCENARIO_READY = "SCENARIO_READY", _("Scenarij pripravljen")
        GENERATING_SCRIPT = "GENERATING_SCRIPT", _("Generiranje skripta")
        SCRIPT_READY = "SCRIPT_READY", _("Skript pripravljen")
        GENERATING_VOICE = "GENERATING_VOICE", _("Generiranje zvoka")
        VOICE_READY = "VOICE_READY", _("Zvok pripravljen")
        GENERATING_SUBTITLES = "GENERATING_SUBTITLES", _("Generiranje podnapisov")
        SUBTITLES_READY = "SUBTITLES_READY", _("Podnapisi pripravljeni")
        GENERATING_SEGMENTS = "GENERATING_SEGMENTS", _("Generiranje segmentov")
        SEGMENTS_READY = "SEGMENTS_READY", _("Segmenti pripravljeni")
        SELECTING_VIDEOS = "SELECTING_VIDEOS", _("Izbiranje video klipov")
        VIDEOS_SELECTED = "VIDEOS_SELECTED", _("Video klipi izbrani")
        RENDERING = "RENDERING", _("Renderiranje končnega videa")
        COMPLETED = "COMPLETED", _("Končano")
        FAILED = "FAILED", _("Napaka")

    class ErrorTypes(models.TextChoices):
        VOICE_GENERATION = "VOICE_GENERATION", _("Napaka pri generiranju zvoka")
        SRT_GENERATION = "SRT_GENERATION", _("Napaka pri generiranju podnapisov")
        SEGMENTS_GENERATION = "SEGMENTS_GENERATION", _(
            "Napaka pri generiranju segmentov"
        )
        RENDERING = "RENDERING", _("Napaka pri renderiranju videa")
        TIMEOUT = "TIMEOUT", _("Timeout pri renderiranju videa")

    class LogoPositions(models.TextChoices):
        TOP_LEFT = "top_left", _("Zgoraj levo")
        TOP_RIGHT = "top_right", _("Zgoraj desno")

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="videos"
    )
    title = models.CharField(max_length=255)
    scenario = models.TextField(null=True, blank=True)
    prompt = models.TextField(default=settings.DEFAULT_PROMPT)
    modify_prompt = models.TextField(blank=True, null=True)
    language = models.CharField(
        max_length=10,
        choices=settings.LANGUAGES,
        default="sl",
        help_text="Language code used for voice generation",
    )
    voice_model = models.CharField(max_length=100, null=True, blank=True)
    voice_file = models.FileField(
        upload_to="voice_files/",
        null=True,
        blank=True,
        help_text="Voice file generated by LLM",
    )
    voice_duration = models.FloatField(
        null=True, blank=True, help_text="Duration of voice file in seconds"
    )
    srt_file = models.FileField(
        upload_to="srt_files/",
        null=True,
        blank=True,
        help_text="Subtitle file in SRT format",
    )
    srt_content = models.TextField(
        blank=True, null=True, help_text="Content of the SRT subtitle file"
    )
    subtitle_style = models.CharField(
        max_length=50,
        default="style1",
        help_text="Selected subtitle style for video rendering",
    )
    subtitle_font_size = models.IntegerField(
        default=12, help_text="Font size for subtitles (in pixels)"
    )
    subtitle_font_family = models.CharField(
        max_length=50, default="Montserrat", help_text="Font family for subtitles"
    )
    subtitle_font_weight = models.CharField(
        max_length=20, default="900", help_text="Font weight for subtitles"
    )
    subtitle_stroke_weight = models.IntegerField(
        default=3, help_text="Stroke weight for subtitles (in pixels)"
    )
    subtitle_shadow = models.IntegerField(
        default=1, help_text="Shadow intensity for subtitles"
    )
    subtitle_vertical_position = models.IntegerField(
        default=10, help_text="Vertical position from bottom in percentage (0-50)"
    )
    subtitle_max_words_per_screen = models.IntegerField(
        null=True,
        blank=True,
        help_text="Maximum number of words displayed on screen at once",
    )
    final_file = models.FileField(
        upload_to="final_videos/",
        null=True,
        blank=True,
        help_text="Final generated video file",
    )
    status = models.CharField(
        max_length=30, choices=Statuses.choices, default=Statuses.CREATED
    )
    error_type = models.CharField(
        max_length=50,
        choices=ErrorTypes.choices,
        blank=True,
        null=True,
        help_text="Type/stage of error",
    )
    error_details = models.TextField(
        blank=True, null=True, help_text="Error details if task failed"
    )
    progress = models.CharField(
        max_length=255,
        default="",
        help_text="Optional field to store progress details for long-running tasks",
    )
    logo = models.ForeignKey(
        "UsersLogo",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        help_text="Optional logo to include in the video",
    )
    logo_position = models.CharField(
        max_length=20,
        choices=LogoPositions.choices,
        default=LogoPositions.TOP_RIGHT,
        help_text="Selected corner for logo placement",
    )
    logo_size_percent = models.PositiveSmallIntegerField(
        default=15,
        validators=[MinValueValidator(5), MaxValueValidator(40)],
        help_text="Logo width as percentage of final video width",
    )
    result_url = models.URLField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    video_segments_prompt = models.TextField(
        blank=True,
        null=True,
        help_text="""
Prompt za določitev ključnih segmentov videa. Na koncu prompta se bo še dodal text:
Za vsak segment mi določi še start in endtime Vrni mi samo python seznam slovarjev v obliki 
[{{"start": "0.00", "end": "5.00", "text": "besedilo", "keywords": ["keyword_eng_1", "keyword_eng_2"]}}, ...]
""",
        default="""
Spodaj imaš transkript scenarija za video in podnapise.
Tekst scenarija razbij v krajše, vsebinsko smiselne segmente in določi kratke ključne besede v angleščini, ki najbolje opisujejo vsebino posameznega segmenta.
Pri določanju ključnih besed upoštevaj tudi kontekst vsebine celotnega scenarija, ne samo posameznih segmentov.
""",
    )

    def __str__(self):
        return f"Task {self.id} - {self.status}"

    @property
    def modify_llm_prompt(self):
        return f"Ukaz:\n{self.modify_prompt}\n\nScenarij:\n{self.scenario}"

    @property
    def srt_from_scenario_prompt(self):
        return f"Generate an SRT subtitle file for the following script:\n\n{self.scenario}"

    @property
    def video_segments_keywords_prompt(self):
        return f"""
Vrni seznam v JSON formatu.
{self.video_segments_prompt}
Časovna enota je sekunda in naj bo vedno tipa float. Start time-i prvega segmenta je "0.00".  Za segmente uporabljaj referenco podnapise, torej naj imajo smisel z besedilom in časom podnapisov.
End time zadnjega segmenta je enak dolžini videa, torej je enak koncu zadnjega podnapisa. Segmenti naj bodo zaporedni in se ne bodo prekrivali. V podnapisih so časovni žigi v formatu HH:MM:SS,MMM. 
Primer za časovno kodo v SRT formatu:
00:00:38,200 --> 00:00:41,610 pomeni start: "38.20", end: "41.61"
Za vsak segment mi določi starttime in endtime. Vrni mi samo json seznam objektov v obliki, kjer so časovni žigi v sekundah.
Odgovor naj vsebuje samo seznam slovarjev, brez dodatnega besedila ali pojasnil ali kode ki nastavi vsebino v spremenljivko!
Spodaj je primer kako naj bo format odgovora:
[{{"start": "0.00", "end": "2.37", "text": "besedilo", "keywords": ["keyword_eng_1", "keyword_eng_2"]}}, {{"start": "2.38", "end": "66.45", "text": "besedilo", "keywords": ["keyword_eng_1", "keyword_eng_2"]}}]
--------
Scenarij:
{self.scenario}
--------
Transkript:
{self.srt_content}
"""


class ProviderTTSModel(models.Model):
    class Providers(models.TextChoices):
        ELEVENLABS = "elevenlabs", "ElevenLabs"
        OPENAI = "openai", "OpenAI"
        GEMINI = "gemini", "Gemini"

    provider = models.CharField(max_length=30, choices=Providers.choices)
    external_id = models.CharField(max_length=120)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    can_do_text_to_speech = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    raw_payload = models.JSONField(default=dict, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["provider", "external_id"],
                name="uniq_provider_tts_model",
            )
        ]
        ordering = ["provider", "name"]

    def __str__(self):
        return f"{self.provider}:{self.external_id} ({self.name})"


class ProviderTTSModelLanguage(models.Model):
    tts_model = models.ForeignKey(
        ProviderTTSModel,
        on_delete=models.CASCADE,
        related_name="languages",
    )
    language_id = models.CharField(max_length=30)
    name = models.CharField(max_length=120)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["tts_model", "language_id"],
                name="uniq_tts_model_language",
            )
        ]
        ordering = ["tts_model", "name"]

    def __str__(self):
        return f"{self.tts_model.external_id}:{self.language_id}"


class VideoSegment(models.Model):
    video = models.ForeignKey(
        GenVideo, related_name="segments", on_delete=models.CASCADE
    )
    text = models.TextField(help_text="Text of the segment")
    order = models.IntegerField(help_text="Order of the segment in the video")
    query = models.TextField(help_text="Query used to retrieve or generate the scene")
    start_time = models.FloatField(help_text="Start time in seconds")
    end_time = models.FloatField(help_text="End time in seconds")
    cut_start_time = models.FloatField(
        help_text="Adjusted start time for cutting the scene", null=True, blank=True
    )
    cut_end_time = models.FloatField(
        help_text="Adjusted end time for cutting the scene", null=True, blank=True
    )
    video_proposals = models.JSONField(
        help_text="List of video proposals with metadata", default=list, blank=True
    )

    def __str__(self):
        return f"segment {self.id} for Video {self.video.id}"

    def duration(self):
        return self.end_time - self.start_time


class UsersLogo(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="logos"
    )
    logo_file = models.FileField(
        upload_to="user_logos/",
        null=True,
        blank=True,
        help_text="User uploaded logo file",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Logo {self.id} for User {self.user.username}"
