from django.conf import settings
from django.db import models

# Create your models here.


class GenVideo(models.Model):
    class Statuses(models.TextChoices):
        CREATED = "CREATED", "Ustvarjen"
        GENERATING_SCENARIO = "GENERATING_SCENARIO", "Generiranje scenarija"
        SCENARIO_READY = "SCENARIO_READY", "Scenarij pripravljen"
        GENERATING_SCRIPT = "GENERATING_SCRIPT", "Generiranje skripta"
        SCRIPT_READY = "SCRIPT_READY", "Skript pripravljen"
        GENERATING_VOICE = "GENERATING_VOICE", "Generiranje zvoka"
        VOICE_READY = "VOICE_READY", "Zvok pripravljen"
        GENERATING_SUBTITLES = "GENERATING_SUBTITLES", "Generiranje podnapisov"
        SUBTITLES_READY = "SUBTITLES_READY", "Podnapisi pripravljeni"
        GENERATING_SEGMENTS = "GENERATING_SEGMENTS", "Generiranje segmentov"
        SEGMENTS_READY = "SEGMENTS_READY", "Segmenti pripravljeni"
        SELECTING_VIDEOS = "SELECTING_VIDEOS", "Izbiranje video klipov"
        VIDEOS_SELECTED = "VIDEOS_SELECTED", "Video klipi izbrani"
        RENDERING = "RENDERING", "Renderiranje končnega videa"
        COMPLETED = "COMPLETED", "Končano"
        FAILED = "FAILED", "Napaka"

    class ErrorTypes(models.TextChoices):
        VOICE_GENERATION = "VOICE_GENERATION", "Napaka pri generiranju zvoka"
        SRT_GENERATION = "SRT_GENERATION", "Napaka pri generiranju podnapisov"
        SEGMENTS_GENERATION = "SEGMENTS_GENERATION", "Napaka pri generiranju segmentov"
        RENDERING = "RENDERING", "Napaka pri renderiranju videa"

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="videos"
    )
    title = models.CharField(max_length=255)
    scenario = models.TextField(null=True, blank=True)
    prompt = models.TextField(default=settings.DEFAULT_PROMPT)
    modify_prompt = models.TextField(blank=True, null=True)
    voice_model = models.CharField(max_length=100, null=True, blank=True)
    voice_file = models.FileField(
        upload_to="voice_files/",
        null=True,
        blank=True,
        help_text="Voice file generated by LLM",
    )
    voice_duration = models.FloatField(
        null=True, blank=True, help_text="Duration of voice file in seconds"
    )
    srt_file = models.FileField(
        upload_to="srt_files/",
        null=True,
        blank=True,
        help_text="Subtitle file in SRT format",
    )
    srt_content = models.TextField(
        blank=True, null=True, help_text="Content of the SRT subtitle file"
    )
    subtitle_style = models.CharField(
        max_length=50,
        default="style1",
        help_text="Selected subtitle style for video rendering",
    )
    subtitle_font_size = models.IntegerField(
        default=12, help_text="Font size for subtitles (in pixels)"
    )
    subtitle_font_family = models.CharField(
        max_length=50, default="Montserrat", help_text="Font family for subtitles"
    )
    subtitle_font_weight = models.CharField(
        max_length=20, default="900", help_text="Font weight for subtitles"
    )
    subtitle_stroke_weight = models.IntegerField(
        default=3, help_text="Stroke weight for subtitles (in pixels)"
    )
    subtitle_shadow = models.IntegerField(
        default=1, help_text="Shadow intensity for subtitles"
    )
    subtitle_vertical_position = models.IntegerField(
        default=10, help_text="Vertical position from bottom in percentage (0-50)"
    )
    final_file = models.FileField(
        upload_to="final_videos/",
        null=True,
        blank=True,
        help_text="Final generated video file",
    )
    status = models.CharField(
        max_length=30, choices=Statuses.choices, default=Statuses.CREATED
    )
    error_type = models.CharField(
        max_length=50,
        choices=ErrorTypes.choices,
        blank=True,
        null=True,
        help_text="Type/stage of error",
    )
    error_details = models.TextField(
        blank=True, null=True, help_text="Error details if task failed"
    )
    result_url = models.URLField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    video_segments_prompt = models.TextField(
        blank=True,
        null=True,
        help_text="""
Prompt za določitev ključnih segmentov videa. Na koncu prompta se bo še dodal text:
Za vsak segment mi določi še start in endtime Vrni mi samo python seznam slovarjev v obliki 
[{{"start": "0.00", "end": "5.00", "text": "besedilo", "keywords": ["keyword_eng_1", "keyword_eng_2"]}}, ...]
""",
        default="""
Spodaj imaš transkript scenarija za video in podnapise.
Tekst scenarija razbij v krajše, vsebinsko smiselne segmente in določi kratke ključne besede v angleščini, ki najbolje opisujejo vsebino posameznega segmenta.
Pri določanju ključnih besed upoštevaj tudi kontekst vsebine celotnega scenarija, ne samo posameznih segmentov.
""",
    )

    def __str__(self):
        return f"Task {self.id} - {self.status}"

    @property
    def modify_llm_prompt(self):
        return f"Ukaz:\n{self.modify_prompt}\n\nScenarij:\n{self.scenario}"

    @property
    def srt_from_scenario_prompt(self):
        return f"Generate an SRT subtitle file for the following script:\n\n{self.scenario}"

    @property
    def video_segments_keywords_prompt(self):
        return f"""
{self.video_segments_prompt}
Časovna enota je sekunda in naj bo vedno tipa float. Start time-i prvega segmenta je "0.00".  Za segmente uporabljaj referenco podnapise, torej naj imajo smisel z besedilom in časom podnapisov.
End time zadnjega segmenta je enak dolžini videa, torej je enak koncu zadnjega podnapisa. Segmenti naj bodo zaporedni in se ne bodo prekrivali. V podnapisih so časovni žigi v formatu HH:MM:SS,MMM. 
Primer za časovno kodo v SRT formatu:
00:00:38,200 --> 00:00:41,610 pomeni start: "38.20", end: "41.61"
Za vsak segment mi določi starttime in endtime Vrni mi samo python seznam slovarjev v obliki, kjer so časovni žigi v sekundah.
Odgovor naj vsebuje samo seznam slovarjev, brez dodatnega besedila ali pojasnil ali kode ki nastavi vsebino v spremenljivko!
Spodaj je primer kako naj bo format odgovora:
[{{"start": "0.00", "end": "2.37", "text": "besedilo", "keywords": ["keyword_eng_1", "keyword_eng_2"]}}, {{"start": "2.38", "end": "66.45", "text": "besedilo", "keywords": ["keyword_eng_1", "keyword_eng_2"]}}]
--------
Scenarij:
{self.scenario}
--------
Transkript:
{self.srt_content}
"""


class VideoSegment(models.Model):
    video = models.ForeignKey(
        GenVideo, related_name="segments", on_delete=models.CASCADE
    )
    text = models.TextField(help_text="Text of the segment")
    order = models.IntegerField(help_text="Order of the segment in the video")
    query = models.TextField(help_text="Query used to retrieve or generate the scene")
    start_time = models.FloatField(help_text="Start time in seconds")
    end_time = models.FloatField(help_text="End time in seconds")
    cut_start_time = models.FloatField(
        help_text="Adjusted start time for cutting the scene", null=True, blank=True
    )
    cut_end_time = models.FloatField(
        help_text="Adjusted end time for cutting the scene", null=True, blank=True
    )
    video_proposals = models.JSONField(
        help_text="List of video proposals with metadata", default=list, blank=True
    )
    video_file = models.FileField(
        upload_to="video_segments/",
        null=True,
        blank=True,
        help_text="Video file for this segment",
    )

    def __str__(self):
        return f"segment {self.id} for Video {self.video.id}"

    def duration(self):
        return self.end_time - self.start_time
