from django.db import models
from django.conf import settings

# Create your models here.


class GenVideo(models.Model):
    class Statuses(models.TextChoices):
        CREATED = "CREATED", "Ustvarjen"
        GENERATING_SCENARIO = "GENERATING_SCENARIO", "Generiranje scenarija"
        SCENARIO_READY = "SCENARIO_READY", "Scenarij pripravljen"
        GENERATING_SCRIPT = "GENERATING_SCRIPT", "Generiranje skripta"
        SCRIPT_READY = "SCRIPT_READY", "Skript pripravljen"
        GENERATING_VOICE = "GENERATING_VOICE", "Generiranje zvoka"
        VOICE_READY = "VOICE_READY", "Zvok pripravljen"
        GENERATING_SUBTITLES = "GENERATING_SUBTITLES", "Generiranje podnapisov"
        SUBTITLES_READY = "SUBTITLES_READY", "Podnapisi pripravljeni"
        GENERATING_SEGMENTS = "GENERATING_SEGMENTS", "Generiranje segmentov"
        SEGMENTS_READY = "SEGMENTS_READY", "Segmenti pripravljeni"
        SELECTING_VIDEOS = "SELECTING_VIDEOS", "Izbiranje video klipov"
        VIDEOS_SELECTED = "VIDEOS_SELECTED", "Video klipi izbrani"
        RENDERING = "RENDERING", "Renderiranje končnega videa"
        COMPLETED = "COMPLETED", "Končano"
        FAILED = "FAILED", "Napaka"

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="videos"
    )
    title = models.CharField(max_length=255)
    start_prompt = models.TextField(help_text="Initial prompt for video generation", null=True, blank=True)
    scenario = models.TextField(null=True, blank=True)
    prompt = models.TextField(default=settings.DEFAULT_PROMPT)
    content_script = models.TextField(blank=True, null=True)
    voice_model = models.CharField(max_length=100, null=True, blank=True)
    voice_file = models.FileField(
        upload_to="voice_files/",
        null=True,
        blank=True,
        help_text="Voice file generated by LLM",
    )
    srt_file = models.FileField(
        upload_to="srt_files/",
        null=True,
        blank=True,
        help_text="Subtitle file in SRT format",
    )
    srt_content = models.TextField(blank=True, null=True, help_text="Content of the SRT subtitle file")
    final_file = models.FileField(
        upload_to="final_videos/",
        null=True,
        blank=True,
        help_text="Final generated video file",
    )
    status = models.CharField(
        max_length=30, choices=Statuses.choices, default=Statuses.CREATED
    )
    result_url = models.URLField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    video_segments_prompt = models.TextField(blank=True, null=True, help_text="""
Prompt za določitev ključnih segmentov videa. Na koncu prompta se bo še dodal text:
Za vsak segment mi določi še start in endtime Vrni mi samo python seznam slovarjev v obliki 
[{{"start": "0.00", "end": "5.00", "text": "besedilo", "keywords": ["keyword_eng_1", "keyword_eng_2"]}}, ...]
""", default="""
Spodaj imaš scenarij videa in transkript scenarija.
Vsebino mi razbij v 3-4 segmente in določi keyworde v angleščini, ki najbolje opisujejo vsebino, po katerih lahko nato iščem videe.
""")

    def __str__(self):
        return f"Task {self.id} - {self.status}"
    
    @property
    def simplify_prompt(self):
        return f"{self.prompt}\n\n{self.scenario}"
    
    @property
    def srt_from_content_script_prompt(self):
        return f"Generate an SRT subtitle file for the following script:\n\n{self.content_script}"
    
    @property
    def video_segments_keywords_prompt(self):
        return f"""
{self.video_segments_prompt}
Časovna enota je sekunda. Start time-i prvega segmenta je "0.00".  Za segmente uporabljaj referenco podnapise, torej naj imajo smisel z besedilom in časom podnapisov.
End time zadnjega segmenta je enak dolžini videa, torej je enak koncu zadnjega podnapisa.
00:00:38,200 --> 00:00:41,610 pomeni start: "38.20", end: "41.61"
Za vsak segment mi določi starttime in endtime Vrni mi samo python seznam slovarjev v obliki 
[{{"start": "0.00", "end": "2.37", "text": "besedilo", "keywords": ["keyword_eng_1", "keyword_eng_2"]}}, ...]
--------
Scenarij:
{self.scenario}
--------
Transkript:
{self.srt_content}
"""


class VideoSegment(models.Model):
    video = models.ForeignKey(
        GenVideo, related_name="segments", on_delete=models.CASCADE
    )
    text = models.TextField(help_text="Text of the segment")
    order = models.IntegerField(help_text="Order of the segment in the video")
    query = models.TextField(help_text="Query used to retrieve or generate the scene")
    start_time = models.FloatField(help_text="Start time in seconds")
    end_time = models.FloatField(help_text="End time in seconds")
    cut_start_time = models.FloatField(
        help_text="Adjusted start time for cutting the scene", null=True, blank=True
    )
    cut_end_time = models.FloatField(
        help_text="Adjusted end time for cutting the scene", null=True, blank=True
    )
    video_proposals = models.JSONField(
        help_text="List of video proposals with metadata", default=list, blank=True
    )
    video_file = models.FileField(
        upload_to="video_segments/",
        null=True,
        blank=True,
        help_text="Video file for this segment",
    )

    def __str__(self):
        return f"segment {self.id} for Video {self.video.id}"
